### ISSUE TITLE
 SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ezh** [react-in-action/letters-social#543]
Chapter 7
```
node -v
v8.9.4
npm -v
5.6.0

NODE_ENV=development BABEL_ENV=development npm test
 FAIL  test/components/nav/navbar.test.js
  ● Test suite failed to run

    /home/ezh/nuclide-test/letters-social/test/setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){/* istanbul ignore next */var cov_2qwcktmx8o = function () {var path = '/home/ezh/nuclide-test/letters-social/test/setup.js',hash = '13d40d1b49cdf23a9ac6062fa17877855d14e3ad',global = new Function('return this')(),gcv = '__coverage__',coverageData = { path: '/home/ezh/nuclide-test/letters-social/test/setup.js', statementMap: { '0': { start: { line: 4, column: 0 }, end: { line: 4, column: 45 } }, '1': { start: { line: 6, column: 0 }, end: { line: 9, column: 2 } }, '2': { start: { line: 12, column: 0 }, end: { line: 32, column: 2 } }, '3': { start: { line: 16, column: 12 }, end: { line: 19, column: 14 } }, '4': { start: { line: 26, column: 8 }, end: { line: 30, column: 10 } } }, fnMap: { '0': { name: '(anonymous_0)', decl: { start: { line: 15, column: 21 }, end: { line: 15, column: 22 } }, loc: { start: { line: 15, column: 27 }, end: { line: 20, column: 9 } }, line: 15

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
```
and so on... All tests are failed.
Solution - https://github.com/facebook/jest/issues/2081#issuecomment-306706600
We need to add one more plugin to .babelrc `transform-es2015-modules-commonjs`

After that all tests are passed as expected.

**Comment by markthethomas** [comment]
@ezh thanks for reporting! Are you open to PRing?

**Comment by markthethomas** [comment]
Closing as this doesn't some to be an issue in current state of release; will re-open if it comes back up
