### ISSUE TITLE
Running `npm run dev` doesn't work

### ISSUE THREAD

**Issue by kieronlanning** [react-in-action/letters-social#546]
Running the above command results in an error:

`ERROR in ./src/index.js
Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing preset: "P:\\react-in-aciton\\letters-social\\node_modules\\babel-preset-react-app\\index.js")
    at Object.<anonymous> (P:\react-in-aciton\letters-social\node_modules\babel-preset-react-app\index.js:47:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\options\option-manager.js:296:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (P:\react-in-aciton\letters-social\node_modules\babel-core\lib\transformation\file\index.js:135:24)
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/index`

**Comment by kieronlanning** [comment]
Setting the NODE_ENV to Development seemed to work.
