### ISSUE TITLE
webpack errors

### ISSUE THREAD

**Issue by glstream** [react-in-action/letters-social#564]
After running 'npm install' and seeding the db. I am getting this error:

JSON Server is running
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letters-social@1.0.0 client:dev: `webpack-dev-server --config ./build/webpack.config.js`

**Comment by glstream** [comment]
I resolved by deleting repo and re cloning.
