### ISSUE TITLE
Node 10 support.

### ISSUE THREAD

**Issue by mario-grgic** [react-in-action/letters-social#573]
npm install fails with node 10.13.0 on macOS 10.14.1.

```
$ npm install

> fsevents@1.1.2 install /Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:../../nan/nan_maybe_43_inl.h112::11215::15 : error: error: no member nonamed  member'ForceSet'  namedin  'ForceSet''v8::Object' in
 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);

         ~~~  ^         ~~~  ^

In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
In file included from In file included from ../../nan/nan.h../../nan/nan.h::198198:
:
In file included from In file included from ../../nan/nan_new.h:../../nan/nan_new.h189::
189:
../../nan/nan_implementation_12_inl.h:../../nan/nan_implementation_12_inl.h337::33728::28 : warning: warning: 'New' 'New'is  isdeprecated  deprecated[-Wdeprecated-declarations] [-Wdeprecated-declarations]

  return v8::StringObject::New(value).As<v8::StringObject>();  return v8::StringObject::New(value).As<v8::StringObject>();

                           ^                           ^

/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h:/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h5052::50523::3 : note: note: 'New' 'New'has  hasbeen  beenexplicitly  explicitlymarked  markeddeprecated  deprecatedhere here

  V8_DEPRECATED("Use Isolate* version",
  V8_DEPRECATED("Use Isolate* version",
  ^
  ^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded /Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.hfrom: 327macro: 29'V8_DEPRECATED': 
note: expanded from macro   declarator __attribute__((deprecated))'V8_DEPRECATED'

                            ^
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18:In file included from  ../fsevents.cc:warning6: :
../../nan/nan.h'MakeCallback': 834is: 18:deprecated:  Use warningMakeCallback(...,:  async_context)
'MakeCallback'       [-Wdeprecated-declarations]is 
deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:                 ^175
:1: /Users/mariogrgic/.node-gyp/10.13.0/include/node/node.hnote:: 175:'MakeCallback'1 :has  been noteexplicitly:  marked'MakeCallback'
       hasdeprecated  beenhere explicitly
 marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:^91:
20: /Users/mariogrgic/.node-gyp/10.13.0/include/node/node.hnote:: 91:expanded20 :from  macro note'NODE_DEPRECATED': 
expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.hIn file included from :../fsevents.cc849::618:
: ../../nan/nan.h:849warning:: 18: 'MakeCallback' iswarning : deprecated: Use'MakeCallback'  MakeCallback(...,is  async_context)deprecated:
       Use[-Wdeprecated-declarations] MakeCallback(...,
 async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h                 ^:
168:1: /Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:168note:: 1:'MakeCallback'  has notebeen:  explicitly'MakeCallback'  markedhas
       beendeprecated  explicitlyhere marked

      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h^:
91:20: /Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:91note:: 20:expanded  from notemacro:  'NODE_DEPRECATED'expanded 
from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h../fsevents.cc::8646::
18:../../nan/nan.h :864:warning18: : 'MakeCallback' warningis:  deprecated: 'MakeCallback'Use  isMakeCallback(...,  deprecated:async_context) 
Use       [-Wdeprecated-declarations]MakeCallback(..., 
async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
                 ^/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h
:161:1:/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h :161:note1: : 'MakeCallback' hasnote : been 'MakeCallback'explicitly  hasmarked 
been       deprecatedexplicitly  heremarked

      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:91:20/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:: 91:20note::  expanded notefrom:  macroexpanded  'NODE_DEPRECATED'from 
macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:911:44: In file included from ../fsevents.cc:warning6: :
../../nan/nan.h'ToString': 911is: 44deprecated:  [-Wdeprecated-declarations]
warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h:      v8::Local<v8::String> string = from->ToString();2454
:10                                           ^:
 note: 'ToString'/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h :has2454 :been10 :explicitly  marked notedeprecated: 
      'ToString'here has
 been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.h:  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);327
:29         ^:
 note: /Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.hexpanded: 327from: 29macro:  'V8_DEPRECATED'
note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
  declarator __attribute__((deprecated))
                            ^
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::921921::2727::  warningwarning: : 'WriteUtf8''WriteUtf8'  isis  deprecateddeprecated  [-Wdeprecated-declarations][-Wdeprecated-declarations]

        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);

                          ^                          ^

/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8.h::26582658::33::  notenote: : 'WriteUtf8''WriteUtf8'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated

            herehere

  V8_DEPRECATED("Use Isolate* version",  V8_DEPRECATED("Use Isolate* version",

  ^  ^

/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.h/Users/mariogrgic/.node-gyp/10.13.0/include/node/v8config.h::327327::2929::  notenote: : expandedexpanded  fromfrom  macromacro  'V8_DEPRECATED''V8_DEPRECATED'

  declarator __attribute__((deprecated))  declarator __attribute__((deprecated))

                            ^                            ^

In file included from ../fsevents.cc:6:
In file included from ../fsevents.cc../../nan/nan.h::61473:
:31:../../nan/nan.h :1473:warning31: : 'MakeCallback' warningis:  deprecated: 'MakeCallback'Use  isMakeCallback(...,  deprecated:async_context) 
Use       [-Wdeprecated-declarations]MakeCallback(..., 
async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
    return scope.Escape(node::MakeCallback(
                              ^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:175:/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h1::175 :1:note : 'MakeCallback'note : has 'MakeCallback'been  hasexplicitly  beenmarked 
explicitly       deprecatedmarked 
here      deprecated
 here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
NODE_DEPRECATED("Use MakeCallback(..., async_context)",^

^
/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h:/Users/mariogrgic/.node-gyp/10.13.0/include/node/node.h91::9120::20 : note: note: expanded expandedfrom  frommacro  macro'NODE_DEPRECATED' 'NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator
    __attribute__((deprecated(message))) declarator
                   ^
                   ^
7 warnings and 1 error generated.
7 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1make: 
*** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR! build error 
ERR! build error 
gyp ERR! gypstack Error: `make` failed with exit code: 2
 gypERR!  ERR! stackstack Error: `make` failed with exit code: 2
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
     at ChildProcess.emit (events.js:182:13)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:182:13)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! gypSystem Darwin 18.2.0
 ERR! System Darwin 18.2.0
gyp ERR! gypcommand  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
ERR! gypcommand  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
ERR! gypcwd  /Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents
ERR!gyp  cwdERR! /Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents
 node -vgyp  v10.13.0
ERR!gyp  node -v v10.13.0
ERR! node-gyp -vgyp v3.8.0
 ERR! gypnode-gyp -v  v3.8.0
ERR! gypnot ok ERR! not ok 
 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> grpc@1.7.3 install /Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gyp ERR! cwd /Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.onstall script
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.ocript
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.c:19:nstall script
In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.h:24:
../deps/grpc/src/core/lib/channel/channel_args.h:22:10: fatal error: 'grpc/compression.h' file not found
#include <grpc/compression.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gyp ERR! cwd /Users/mariogrgic/Development/Node-js/letters-social/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mariogrgic/.npm/_logs/2018-11-04T15_14_15_133Z-debug.log
$ 
```

**Comment by markthethomas** [comment]
hey! looks like an issue w/ deps (nothing in the project that wouldn't support node 10 afaik). would you be open to looking at a PRing or using node 8?

**Comment by mario-grgic** [comment]
Yes, I'm using node 8 where this repo works.

**Comment by markthethomas** [comment]
Cool! I don't have plans to support node 10 in the immediate future, but will probably open up support early next year. I would recommend using 8, especially since there shouldn't be anything in 10 that changes how the app works/runs/etc. 👍
