### ISSUE TITLE
Problems with Chapter 4

### ISSUE THREAD

**Issue by j-terranova** [react-in-action/letters-social#599]
I have problems running the npm run db:seed and npm run dev.

I have uninstalled and reinstalled node_modules.  I then had to uninstall and reinstall node-sass as I was getting  message that the version I had would not run with Windows 64bit.

When I ran dbseed I had the error you (Mark T) indicated from about 2 years back and made the recommended changes to pluggins for .babelrc .

When I ran db:seed I had errors per the log below.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node.exe',
1 verbose cli   'C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'db:seed'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'predb:seed', 'db:seed', 'postdb:seed' ]
5 info lifecycle letters-social@1.0.0~predb:seed: letters-social@1.0.0
6 info lifecycle letters-social@1.0.0~db:seed: letters-social@1.0.0
7 verbose lifecycle letters-social@1.0.0~db:seed: unsafe-perm in lifecycle true
8 verbose lifecycle letters-social@1.0.0~db:seed: PATH: C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\jterr\Documents\NodeProjects\GettingStarted\;C:\Users\jterr\Documents\NodeProjects\Node\;C:\Program Files\Git\cmd;C:\Program Files\OpenSSL-Win64\bin;C:\Users\jterr\AppData\Local\Microsoft\WindowsApps;C:\Users\jterr\AppData\Roaming\npm;C:\Users\jterr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\heroku\bin;
9 verbose lifecycle letters-social@1.0.0~db:seed: CWD: C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4
10 silly lifecycle letters-social@1.0.0~db:seed: Args: [ '/d /s /c', 'node -r @std/esm db/seed.js' ]
11 silly lifecycle letters-social@1.0.0~db:seed: Returned: code: 134  signal: null
12 info lifecycle letters-social@1.0.0~db:seed: Failed to exec db:seed script
13 verbose stack Error: letters-social@1.0.0 db:seed: `node -r @std/esm db/seed.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid letters-social@1.0.0
15 verbose cwd C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node.exe" "C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "db:seed"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 134
22 error letters-social@1.0.0 db:seed: `node -r @std/esm db/seed.js`
22 error Exit status 134
23 error Failed at the letters-social@1.0.0 db:seed script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Comment by rochitsen** [comment]
I have the exact same issue.

**Comment by BobMakhlin** [comment]
Where is the author?

**Comment by rochitsen** [comment]
@BobMakhlin I was able to resolve it. Will post the details soon here. I think I used a different version of node.

**Comment by bzdgn** [comment]
Any updates? I cannot make it run neither on Windows nor on Mac, seems to be a node version issue.
