### ISSUE TITLE
Error concerning node-sass while running npm run dev

### ISSUE THREAD

**Issue by brtchkv** [react-in-action/letters-social#601]
> letters-social@1.0.0 styles ~/letters-social
> node-sass -q src/styles/styles.scss -o static/

node[15686]: ../src/node_file.cc:836:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) == (4)' failed.
 1: 0x10007e9b3 node::Abort() [/usr/local/bin/node]
 2: 0x10007e75b node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 3: 0x1000882b9 node::fs::LStat(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001e1650 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 5: 0x1001e0c2f v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001e0330 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x100930d99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
[nodemon] app crashed - waiting for file changes before starting...
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '~/letters-social/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:854:3)
    at Object.getInstalledBinaries (~/letters-social/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (~/letters-social/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (~/letters-social/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (~/letters-social/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (~/letters-social/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (~/letters-social/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '~/letters-social/node_modules/node-sass/vendor'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letters-social@1.0.0 styles: `node-sass -q src/styles/styles.scss -o static/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the letters-social@1.0.0 styles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-07-11T17_47_07_879Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letters-social@1.0.0 styles:w: `npm run styles && node-sass src/styles/styles.scss -o static/ -w src/styles --watch --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the letters-social@1.0.0 styles:w script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-07-11T17_47_07_923Z-debug.log
ERROR: "styles:w" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letters-social@1.0.0 dev: `cross-env NODE_ENV=development npm-run-all -p api client:dev server:dev styles:w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the letters-social@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brtchkv** [comment]
solved by installing node with 8.X version with `nvm`.  Also changed `webpack-dev-middleware` version to 3.7.2
