### ISSUE TITLE
there are some question in charptar 6!!

### ISSUE THREAD

**Issue by GrowUpXin** [react-in-action/letters-social#604]
![image](https://user-images.githubusercontent.com/30682583/92571325-8efa6b80-f2b5-11ea-905a-d1c402c79268.png)

**Comment by GrowUpXin** [comment]
and when i press the button submit it take error show that  
TypeError: Cannot read property 'toString' of undefined at F:\react\letters-social\node_modules\lodash-id\src\index.js:37:51 at baseFindIndex (F:\react\letters-social\node_modules\lodash\lodash.js:823:11) at findIndex (F:\react\letters-social\node_modules\lodash\lodash.js:7275:14) at Function.find (F:\react\letters-social\node_modules\lodash\lodash.js:5098:21) at Function.getById (F:\react\letters-social\node_modules\lodash-id\src\index.js:35:17) at F:\react\letters-social\node_modules\lodash\lodash.js:4379:28 at arrayReduce (F:\react\letters-social\node_modules\lodash\lodash.js:704:21) at baseWrapperValue (F:\react\letters-social\node_modules\lodash\lodash.js:4378:14) at LodashWrapper.wrapperValue (F:\react\letters-social\node_modules\lodash\lodash.js:9067:14) at F:\react\letters-social\node_modules\json-server\lib\server\router\plural.js:32:74

**Comment by GrowUpXin** [comment]
![image](https://user-images.githubusercontent.com/30682583/92571705-07612c80-f2b6-11ea-883c-a0d033eebb92.png)
the zero is my new message
the one is zhe api provide when i add this posts the error happend

**Comment by GrowUpXin** [comment]
![image](https://user-images.githubusercontent.com/30682583/92572271-c7e71000-f2b6-11ea-872b-f7309ed60152.png)
